baseURL = "https://www.osrtos.com/"
languageCode = "en-us"
title = "OSRTOS"
theme = "unify"


googleAnalytics = "UA-83586141-1"

[taxonomies]


[params]
  mainSections = ["rtos"]
  favicon = "favicon.ico"
  env= "production"

[menu]

  [[menu.main]]
    identifier = "rtos"
    name = "RTOS"
    url = "/"
    weight = -110

  [[menu.main]]
    identifier = "library"
    name = "Library"
    url = "/library/"
    weight = -100
